name: holidayinnexpressmovil
description: "A new Flutter project."

# Evita que el proyecto se publique en pub.dev
publish_to: 'none'

# Versión de la app
version: 1.0.8+1

# Versión de Flutter y Dart
environment:
  sdk: ^3.7.0

# Dependencias necesarias para el proyecto
dependencies:
  flutter:
    sdk: flutter

  # Iconos de Cupertino (iOS)
  cupertino_icons: ^1.0.8

  # Plugin para generar códigos QR
  qr_flutter: ^4.1.0

  provider: ^6.1.1

  shared_preferences: ^2.5.2
  http: ^1.3.0
  dio: ^5.8.0+1
  logger: ^2.5.0
  video_player: ^2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de lint para mejorar la calidad del código
  flutter_lints: ^2.0.0

  # Plugin para cambiar el ícono de la app
  flutter_launcher_icons: ^0.13.1

# Configuración específica de Flutter
flutter:
  # Habilita los iconos de Material Design
  uses-material-design: true

  # Archivos de imágenes y otros recursos
  assets:
    - assets/logo.png
    - assets/holidayinnexpressbanner.png
    - assets/holidayinnexpressbanner-sinfondo.png
    - assets/icon_logo.png
    - assets/check-in.jpg
    - assets/check-out.jpg
    - assets/DevMaceLogoB.png
    - assets/DevMaceLogoW.png

# Configuración para cambiar el ícono de la app
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_logo.png" # Ruta correcta del icono
  adaptive_icon_foreground: "assets/icon_logo.png" # Usa el mismo icono si no tienes foreground
  adaptive_icon_background: "#233567" # Color de fondo para íconos adaptativos

